# Generated by Django 3.2.8 on 2021-10-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0005_coursesundertaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesundertaken',
            name='joincode',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
