# Generated by Django 3.2.8 on 2021-10-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0006_coursesundertaken_joincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submittedfile',
            field=models.FileField(blank=True, upload_to='Documents/'),
        ),
    ]
