# Generated by Django 3.2.8 on 2021-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0007_alter_submission_submittedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submittedfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
