# Generated by Django 3.2.8 on 2021-10-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0008_auto_20211023_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
