# Generated by Django 3.2.8 on 2021-11-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0010_ta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ta',
            name='edit_privileges',
            field=models.CharField(choices=[('basic', 'basic'), ('intermediate', 'intermediate'), ('instructor level', 'instructor level')], max_length=200, null=True),
        ),
    ]
