# Generated by Django 3.2.8 on 2021-11-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0012_auto_20211126_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
