# Generated by Django 3.2.8 on 2021-11-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0013_auto_20211126_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
