# Generated by Django 3.2.8 on 2021-11-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0022_assignment_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='csvfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
