# Generated by Django 3.2.8 on 2021-11-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0025_alter_assignment_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='histogram',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
