# Generated by Django 3.2.8 on 2021-11-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0026_assignment_histogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='histogram',
        ),
    ]
